/* Run with Playwright installed. BROWSER_EXECUTABLE may point to an existing Chromium binary.
   Start python -m http.server 8080 from the parent directory, then:
   NODE_PATH=/path/to/node_modules BROWSER_EXECUTABLE=/path/to/chrome node tools/browser-tests.cjs
   BASE_URL defaults to the extracted project subdirectory. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||undefined,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1440,height:1100},timezoneId:'America/Chicago'});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const base=process.env.BASE_URL||'http://127.0.0.1:8080/orthodox-daily-main/';
 const results=[];const pass=s=>{results.push(s);console.log('PASS',s)};
 const navigate=async view=>page.evaluate(v=>document.dispatchEvent(new CustomEvent('orthodox:navigate',{detail:v})),view);
 const ready=async()=>page.waitForFunction(()=>document.querySelectorAll('#prayerLibrary .prayer-item').length===18);
 const personal=()=>page.evaluate(()=>window.OrthodoxStore.snapshot());
 try{
 await page.goto(base);await ready();
 await page.evaluate(()=>navigator.serviceWorker.ready);
 await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
 await page.evaluate(()=>{localStorage.setItem('orthodoxDailyJournal',JSON.stringify({'2026-09-01':'Original journal entry'}));localStorage.setItem('orthodoxDailyFavorites',JSON.stringify(['jesus']));});
 await page.reload();await ready();pass('All 18 prayers and calendar load under a project subpath');
 await page.locator('.retreat-hero [data-session=jesus]').click();await page.locator('#sessionDialog').waitFor({state:'visible'});
 await page.locator('#sessionDuration').selectOption('1');await page.clock.install();await page.locator('#sessionStart').click();await page.clock.fastForward(2000);await page.locator('#sessionStart').click();const paused=await page.locator('#sessionCountdown').textContent();await page.clock.fastForward(10000);assert.equal(await page.locator('#sessionCountdown').textContent(),paused);await page.locator('#sessionStart').click();await page.clock.fastForward(61000);await page.evaluate(()=>document.dispatchEvent(new Event("visibilitychange")));assert.equal(await page.locator('#sessionCountdown').textContent(),'00:00');assert(await page.locator('#sessionStart').isDisabled());await page.locator('#sessionComplete').click();assert(await page.locator('#sessionComplete').isDisabled());await page.locator('#closeSession').click();pass('Session timer counts, pauses, resumes, and completes once');
 await navigate('reflect');await page.locator('#reflectionMood').selectOption('Grateful');await page.locator('#gratitudeText').fill('A kindness today <img src=x onerror=alert(1)>');await page.locator('#surrenderText').fill('Tomorrow’s worries');await page.locator('#kindnessText').fill('Call a friend');await page.locator('#reflectionForm button[type=submit]').click();const date=await page.locator('#reflectionDate').inputValue();assert.equal((await personal()).reflections[date].mood,'Grateful');assert.equal(await page.locator('#reflectionHistory img').count(),0);
 await page.locator('#intentionText').fill('For my family');await page.locator('#intentionForm button[type=submit]').click();await page.locator('[data-edit-intention]').click();await page.locator('#intentionText').fill('For my family and friends');await page.locator('#intentionForm button[type=submit]').click();await page.locator('[data-intention]').check();assert.equal((await personal()).intentions[0].text,'For my family and friends');assert.equal((await personal()).intentions[0].done,true);pass('Reflections and intentions save, edit, check off, and escape user text');
 await navigate('rule');await page.locator('#profileName').fill('Stephen');await page.locator('#readingSize').selectOption('large');await page.locator('#profileForm button').click();await page.locator('[data-rule-choice=gratitude]').check();await page.locator('#fullRule [data-practice=gratitude]').check();assert((await personal()).rule.includes('gratitude'));
 await page.reload();await ready();assert.match(await page.locator('#welcomeTitle').textContent(),/Stephen/);assert(await page.locator('body').evaluate(x=>x.classList.contains('large-reading')));assert.equal((await personal()).reflections[date].kindness,'Call a friend');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('orthodoxDailyJournal'))['2026-09-01']),'Original journal entry');pass('Profile, reading size, rule, reflection, intentions, and original journal survive reload');
 await page.locator('#continuePath').click();await page.locator('#sessionComplete').click();await page.keyboard.press('Escape');assert.deepEqual((await personal()).path,[0]);pass('Seven-practice course records completion; Escape closes the dialog');
 await navigate('prayers');await page.locator('#prayerSearch').fill('gratitude');assert(await page.locator('#prayerLibrary .prayer-item').count()>0);await page.locator('#prayerSearch').fill('');await page.locator('#favoritesOnly').check();assert.equal(await page.locator('#prayerLibrary .prayer-item').count(),1);await page.locator('#favoritesOnly').uncheck();pass('Prayer search and existing favorites still work');
 await navigate('tools');const downloadPromise=page.waitForEvent('download');await page.locator('#exportData').click();const dl=await downloadPromise;const backup=JSON.parse(await fs.readFile(await dl.path(),'utf8'));assert(backup.companion.reflections[date]);assert.equal(backup.journal['2026-09-01'],'Original journal entry');
 await page.evaluate(()=>window.OrthodoxStore.update(d=>{d.profile.name='Changed';}));await page.locator('#importData').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForFunction(()=>window.OrthodoxStore.snapshot().profile.name==='Stephen');
 const bad=JSON.parse(JSON.stringify(backup));bad.companion.version=999;bad.journal={'2026-09-01':'Should not overwrite'};await page.locator('#importData').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('unsupported'));assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('orthodoxDailyJournal'))['2026-09-01']),'Original journal entry');pass('Full backup restores old and new data; invalid companion backup is rejected before mutation');
 await navigate('rule');const reminderPromise=page.waitForEvent('download');await page.locator('#downloadReminder').click();const reminder=await reminderPromise;const ics=await fs.readFile(await reminder.path(),'utf8');assert(ics.includes('RRULE:FREQ=DAILY'));assert(ics.includes('BEGIN:VALARM'));pass('Daily reminder exports a recurring event with an alarm');
 await navigate('churches');await page.locator('#churchName').fill('Test Parish');await page.locator('#churchCity').fill('Dallas');await page.locator('#churchForm button[type=submit]').click();assert.match(await page.locator('#churchList').textContent(),/Test Parish/);pass('Original parish creation works');
 for(const width of [390,430,768,1440]){await page.setViewportSize({width,height:932});for(const view of ['home','prayers','reflect','rule','explore','today','calendar','churches','icons','martyrs','history','tools','about']){await navigate(view);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,`${view} overflows at ${width}px`);}}
 pass('All 13 views fit 390, 430, 768, and 1440 pixel widths');
 await page.setViewportSize({width:1440,height:1100});await navigate('home');await page.locator('#profileName').evaluate(x=>{});await page.screenshot({path:process.env.DESKTOP_SHOT||'/tmp/orthodox-desktop-tested.png',fullPage:true});await page.setViewportSize({width:430,height:932});await page.screenshot({path:process.env.MOBILE_SHOT||'/tmp/orthodox-mobile-tested.png',fullPage:true});
 await context.setOffline(true);await page.reload();await ready();assert.match(await page.locator('#connectionState').textContent(),/offline/);await navigate('reflect');assert.equal(await page.locator('#kindnessText').inputValue(),'Call a friend');assert(await page.locator('.retreat-hero img').evaluate(x=>x.complete&&x.naturalWidth>0));pass('Offline reload retains complete prayer library, photograph, and saved reflections');
 await context.setOffline(false);assert.deepEqual(errors,[]);pass('No uncaught browser JavaScript errors');
 console.log(JSON.stringify({passed:results.length,results},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
